x

diff --git a/patch/profile b/patch/profile
--- a/patch/profile
+++ b/patch/profile
@@ -18,14 +18,13 @@ cat <<EOF
 $(echo -e "${Red}Run     Time:	${Sys_time}${White}")
 $(echo -e "${Yellow}$(uname -n)/${TARGET_PROFILE}")
 $(echo -e "${Red}CPU    Model:	${CPU_Model}${White}")
-$(echo -e "${Blue}Mem    Total:	${Mem_sum}${White}")
 Overlay /TMP:	${Overlay_Available} / ${Tmp_Available}
+$(echo -e "${Blue}Mem    Total:	${Mem_sum}${White}")
 FIRWare  Ver:	$(uname -rs)$([ -n "${TEMP}" ] && echo -e "${TEMP}")
 $(echo -e "${Green}TARGET  Info:	${ARCH}${White}")
 $(echo -e "${Red}IPv4 Address:	${IP_Address}${White}")
 EOF
 }
-
 
 White="\e[0m"
 Yellow="\e[33m"
@@ -45,7 +44,6 @@ function ER() {
 function EB() {
   echo
   echo -e "${Blue} $1${Font}"
-  echo
 }
 function EG() {
   echo -e "${Green} $1${Font}"
@@ -54,17 +52,339 @@ function EW() {
   echo -e "${White} $1${Font}"
 }
 
+function k_theme() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+read -p "是否恢复向导和默认主题?(Do you want to restore the wizard and default theme?)[Y/n]:" YN
+
+case ${YN} in
+[Yy]) 
+    ER "已恢复向导和默认主题(The wizard and default theme has been restored.)..."
+    [  -s /etc/init.d/advancedplus ] && /etc/init.d/advancedplus reset   
+    uci set luci.main.mediaurlbase='/luci-static/kucat'
+    uci set luci.themes.KuCat=/luci-static/kucat
+    uci set luci.themes.Bootstrap='/luci-static/bootstrap'
+    uci commit luci
+    uci set argon.@global[0].bing_background=0
+    uci commit argon
+    /etc/init.d/rpcd restart
+    rm -rf /etc/config/wizard
+    rm -rf /etc/config/netwizard_hide
+    sleep 5
+    . /etc/profiles 
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    . /etc/profiles
+;;
+*)
+    ER "输入正确选择(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+function k_poweroff() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+read -p "是否确定关闭系统？(Are you sure to shut down the system)[Y/n]:" YN
+case ${YN} in
+[Yy]) 
+    ER "正在关闭系统中，请稍等(Shutting down the system, please wait)..."
+    poweroff -f
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    . /etc/profiles
+;;
+*)
+    ER "输入正确选择(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+function k_change_ip() {
+  echo 
+  echo -e " q. 返回(return) ,当前IPv4：`ip -4 a | grep 'br-lan' | grep 'inet' | awk '{print $2}' | awk -F '/' '{print $1}'`"
+  export k_ip="请输入新IPv4地址(Input new IPv4)"
+  echo
+  while :; do
+  domainy=""
+  read -p " ${k_ip}：" keyip
+  if [[ -n "${keyip}" ]] && [[ "$(echo ${keyip} |grep -Eoc '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+')" == '1' ]]; then
+    keyipy="Y"
+  fi 
+    if [[ -n "${keyip}" ]] && [[ ${keyip} == 'q'  ||  ${keyip} == 'Q'  ]]; then
+    keyipy="Q"
+  fi
+
+  case $keyipy in
+  Y)
+    export keyipn="${keyip}"
+    echo "修改中，请稍等...( please wait... )" 
+    for i in `seq 1 600`; do
+		mount | grep overlayfs | grep 'workdir=/overlay/work' >/dev/null  2>&1
+		test $? -eq 0 && break
+		sleep 2
+    done
+    uci set network.lan.ipaddr="${keyip}"
+    uci commit network
+    ER "您的IP已经改为(Your IP has been changed to)：${keyip}！"
+    [ -s /etc/config/netwizard ] && uci -q set netwizard.default.lan_ipaddr="${keyip}" && uci commit netwizard 
+    /etc/init.d/network restart
+    sleep 8
+    uci set network.lan.ipaddr="${keyip}"
+    uci commit network
+    /etc/init.d/network restart
+    . /etc/profiles 
+  ;; 
+
+ Q)
+    . /etc/profiles 
+
+;;
+
+  *) 
+  echo 
+  echo -e " q. 返回(return) ,当前IPv4：`ip -4 a | grep 'br-lan' | grep 'inet' | awk '{print $2}' | awk -F '/' '{print $1}'`"
+  export k_ip="输入正确格式IP地址[x.x.x.x](enter IP address format[x.x.x.x])"
+  ;;
+  esac
+  done
+}
+
+function k_clear() {
+while :; do 
+echo -e "\n q. 返回(return)"
+read -p "否清空密码并重启？(Clear password and Reboot)[Y/n]：" YN
+case ${YN} in
+[Yy]) 
+    if [[ "$USER" == "admin" ]]; then
+      sed -i 's/admin:.*/admin::0:0:99999:7:::/g' /etc/shadow
+      passwd -d root
+    else
+      passwd -d root
+    fi
+    goreboot
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    sleep 2
+    . /etc/profiles 
+
+;;
+*)
+    ER "输入正确选择!(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+function k_reboot() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+read -p "是否重启系统(Whether to restart the system)[Y/n]:" YN
+case ${YN} in
+[Yy]) 
+    ER "系统重启中(System is restarting)..."
+    uci set argon.@global[0].bing_background=0
+    uci commit argon
+    reboot -f
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+;;
+[Qq])
+    sleep 2
+    . /etc/profiles 
+
+;;
+*)
+    ER "输入正确选择!(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+function k_firstboot() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+read -p "是否恢复出厂设置(Restore factory settings)?[Y/y]or[N/n]:" YN
+case ${YN} in
+[Yy]) 
+    ER "已经恢复出厂设置,系统重启中(The factory settings have been restored, and the system is restarting)..." 
+    firstboot -y
+    reboot -f
+    goreboot
+;;
+[Nn])
+    EW "取消返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    sleep 2
+    . /etc/profiles 
+
+;;
+*)
+    ER "输入正确选择!(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+
+function k_kmodregdrv() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+echo -e "\n 装载全部驱动可能对系统有影响.(May have an impact on the system stability.)"
+read -p "是否确定?(are you sure? )[Y/n]:" YN
+
+case ${YN} in
+[Yy]) 
+
+    echo
+    ER "正在装载中，请稍等。。。(In mount, Please wait....)"
+    bash /etc/kmodreg drv 2 > /dev/null 2>&1 
+    echo
+    EY "已装载全部的网卡驱动！(All NIC drivers are loaded!)"
+    echo
+    sleep 5
+    . /etc/profiles 
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    . /etc/profiles
+;;
+*)
+    ER "输入正确选择(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+
+
+function k_kmodregdocker() {
+echo
+while :; do
+echo -e "\n q. 返回(return)"
+read -p "是否装载docker服务?(Whether to load Docker service?)[Y/n]:" YN
+
+case ${YN} in
+[Yy]) 
+
+    echo
+    ER "正在装载中，请稍等。。。(In mount, Please wait....)"
+    bash /etc/kmodreg docker 2 > /dev/null 2>&1 
+    echo
+    EY "docker服务装载成功！请重新登录！(Docker service successfully loaded!)"
+    echo
+    sleep 5
+    . /etc/profiles 
+;;
+[Nn])
+    EW "返回主菜单(return)"
+    sleep 2
+    . /etc/profiles 
+
+;;
+[Qq])
+    . /etc/profiles
+;;
+*)
+    ER "输入正确选择(Enter the correct choice!)"
+;;
+esac
+done
+}
+
+function Check_Pkg() {
+	while [[ $1 ]];do
+		CMD=$(echo $1 | cut -d ':' -f1)
+		PKG=$(echo $1 | cut -d ':' -f2)
+		[[ -z ${PKG} ]] && PKG=${CMD}
+		if [[ $(CHECK_PKG ${CMD}) == false ]]
+		then
+			if_False=1
+			ECHO r "\n缺少软件包(Missing package):[${PKG}]"
+		fi
+		shift
+	done
+	if [[ ${if_False} == 1 ]]
+	then
+		sleep 2
+		return 1
+	else
+		return 0
+	fi
+}
+function CHECK_PKG() {
+	which $1 > /dev/null 2>&1
+	[[ $? == 0 ]] && echo true || echo false
+}
+goreboot() {
+  if [[ 0 -eq $? ]]; then
+    ER "$1 完成,正在为您重启系统(Done, restarting the system for you)"
+    reboot -f
+  else
+    ER "$1 失败 (invalid)"
+    sleep 2
+    . /etc/profiles 
+
+  fi
+}
 clear
 [ -e /tmp/.failsafe ] && export FAILSAFE=1
+if ( grep -qs '^root::' /etc/shadow && \
+     [ -z "$FAILSAFE" ] )
+then
+cat << EOF
+================== WARNING! ====================
+There is no root password defined on this device!
+Use the "passwd" command to set up a new password
+in order to prevent unauthorized SSH logins.
+------------------------------------------------
+EOF
+fi
 [ -f /etc/banner ] && echo -e "${Skyb}$(cat /etc/banner)${White}"
 [ -n "$FAILSAFE" ] && cat /etc/banner.failsafe
-
 Sysinfo
-
 grep -Fsq '/ overlay ro,' /proc/mounts && {
 	echo -e "${Red}Your JFFS2-partition seems full and overlayfs is mounted read-only."
 	echo -e "Please try to remove files from /overlay/upper/... and reboot!${}"
 }
+
 
 export PATH="/usr/sbin:/usr/bin:/sbin:/bin"
 export HOME=$(grep -e "^${USER:-root}:" /etc/passwd | cut -d ":" -f 6)
@@ -83,13 +403,6 @@ case "$TERM" in
 		export PS1='\[\e]0;\u@\h: \w\a\]'$PS1
 		;;
 esac
-[ -x /bin/more ] || alias more='less'
-[ -x /usr/bin/vim ] && alias vi='vim' || alias vim='vi'
-
-alias menu='zsh'
-alias dh='df -h'
-alias ls='ls --color=auto'
-alias top='top -d 1'
 
 [ -n "$FAILSAFE" ] || {
 	for FILE in /etc/profile.d/*.sh; do
@@ -98,17 +411,101 @@ alias top='top -d 1'
 	unset FILE
 }
 
-if ( grep -qs '^root::' /etc/shadow && \
-     [ -z "$FAILSAFE" ] )
-then
-cat << EOF
-================== WARNING! ====================
-There is no root password defined on this device!
-Use the "passwd" command to set up a new password
-in order to prevent unauthorized SSH logins.
-------------------------------------------------
-EOF
-fi
-EG " menu->调用菜单(Call Menu) 进阶设置可禁用/显示SSH登陆菜单 "
-EW ""
-/usr/bin/zsh
+function mainmenu() {
+  ER "     Sirdpboy快捷命令菜单(Shortcut Command Menu)   "
+  EG "  menu->调用菜单(Call Menu) 进阶设置中可禁用/显示此快捷菜单 "
+  EY " 1. 修改后台IPv4地址(Modify IPv4 address)"
+  EY " 2. 清除密码并重启(Clear password and Reboot)"
+  EY " 3. 修复向导和主题(Restore wizard default theme)"
+  EY " 4. 重启系统(Reboot)         5. 关闭系统(Shutdown)"    
+  EY " 6. 重置系统(Reset System)   7. 网络检查(Check Network)"
+  EY " 8. 释放内存(free Memory)    9. 停止家长控制(Stop Parentcontrol)"
+  EY " 10. 装载全部网卡驱动(Load all network card drivers)"
+  EY " 11. 装载docker服务(Loading Docker Service)"
+  EW " 0. 退出本快捷菜单(Exit)"
+  echo
+  KEY="请输入功能编号(Please Enter)"
+  while :; do
+  read -p " ${KEY}： " CHOOSE
+  case $CHOOSE in
+    1)
+      k_change_ip
+    ;;
+    2)
+      k_clear
+    break
+    ;;
+    3)
+      k_theme
+    ;;
+    4)
+      k_reboot
+    break
+    ;;
+    5)
+      k_poweroff
+    break
+    ;;
+    6)
+      k_firstboot
+    break
+    ;;
+    7)
+	ping 114.114.114.114 -c 1 -W 2 > /dev/null 2>&1 && \
+	EY  " 基础114网络连接正常!(Basic 114 network connection is OK!)" || EG  " 基础114网络连接错误!(Basic 114 network connection error!)"
+	nslookup -type=a baidu.com > /dev/null 2>&1 &&\
+	EY  " 基础 IPv4 DNS 解析正常!(Basic IPv4 DNS resolution is OK!)" || EG  " 基础 IPv4 DNS 解析错误!(Basic IPv4 DNS resolution error!)"
+	Google_Check=$(curl -I -s --connect-timeout 3 http://www.google.com/generate_204 -w %{http_code} | tail -n1)
+	case ${Google_Check} in
+	204)
+		EY " Google 连接正常!(Google connection is OK!)"
+	;;
+	*)
+		EG " Google 连接错误!(Google connection is error!)"
+	;;
+	 esac
+		ER " "
+	 sleep 5
+    . /etc/profiles 
+    ;;
+    8)
+        EY " 刷新状态清除内存完成!(Refresh status clear memory completed!)"
+        sync && echo 3 > /proc/sys/vm/drop_caches
+        rm -rf /tmp/luci*
+	ER " "
+    sleep 5
+    . /etc/profiles 
+    ;;
+    9)
+      EY " 停卡家长控制插件成功!(Stop Parentcontrol completed!)"
+      EW " "
+      /etc/init.d/parentcontrol stop
+    sleep 5
+    . /etc/profiles 
+    ;;
+    10)
+       k_kmodregdrv
+    ;;
+    11)
+       k_kmodregdocker
+    ;;
+    0)
+      EW " 退出程序成功(Exit the program successfully)"
+      EW " "
+      goexit
+    ;;
+    q)
+      EW " 退出程序成功(Exit the program successfully)"
+      EW " "
+      goexit
+    ;;
+    *)
+     KEY="请输入数字(please enter a number)"
+    ;;
+    esac
+    done
+}
+goexit() {
+  exit
+}
+mainmenu
