u

diff --git a/patch/profile b/patch/profile
--- a/patch/profile
+++ b/patch/profile
@@ -6,16 +6,22 @@ if grep -Eq "x86" "/etc/openwrt_release" ; then
 else
 	DISTRIB_ARCH=${DISTRIB_ARCH}	
 fi
-local IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
+local IP_Address=`ip -4 a | egrep "br-lan" | grep "inet" | awk '{print $2}'`
+local CPU_Model=$(awk -F ':[ ]' '/model name/{printf ($2);exit}' /proc/cpuinfo)
+local Mem_sum=$(free | grep Mem | awk '{a=$2/1024} {printf("%dMB\n",a)}')
 local Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
 local Tmp_Available="$(df -h | grep "/tmp" | awk '{print $4}' | awk 'NR==1')"
 local TEMP=$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}')
+local Sys_time=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60;d=($1%60)} {printf("%d 天 %d 小时 %d 分钟 %d 秒\n",a,b,c,d)}' /proc/uptime)
 cat <<EOF
 $(echo -e "${Yellow}$(uname -n)/${TARGET_PROFILE}")
-$(echo -e "${Green}TARGET Info:	${DISTRIB_ARCH}${White}")
-FIRWare Ver:	$(uname -rs)$([ -n "${TEMP}" ] && echo -e "${TEMP}")
-$(echo -e "${Red}IP  Address:	${IP_Address}${White}")
-OverlaySIZE:	${Overlay_Available} / ${Tmp_Available}
+$(echo -e "${Red}CPU    Model:	${CPU_Model}${White}")
+$(echo -e "${Blue}Mem    Total:	${Mem_sum}${White}")
+$(echo -e "${Green}TARGET  Info:	${DISTRIB_ARCH}${White}")
+FIRWare  Ver:	$(uname -rs)$([ -n "${TEMP}" ] && echo -e "${TEMP}")
+$(echo -e "${Red}IPv4 Address:	${IP_Address}${White}")
+Overlay SIZE:	${Overlay_Available} / ${Tmp_Available}
+$(echo -e "${Red}Run     Time:	${Sys_time}${White}")
 
 EOF
 }
@@ -29,31 +35,33 @@ Green="\e[32m"
 Div="${Grey}|${White}"
 
 function EY() {
-  echo -e "${Yellow} $1 ${Font}"
+  echo -e "${Yellow} $1${Font}"
 }
 function ER() {
   echo
-  echo -e "${Red} $1 ${Font}"
+  echo -e "${Red} $1${Font}"
 }
 function EB() {
   echo
-  echo -e "${Blue} $1 ${Font}"
+  echo -e "${Blue} $1${Font}"
   echo
 }
 function EG() {
-  echo -e "${Green} $1 ${Font}"
+  echo -e "${Green} $1${Font}"
 }
 function EW() {
-  echo -e "${White} $1 ${Font}"
+  echo -e "${White} $1${Font}"
 }
 
 function k_theme() {
 echo
 while :; do
-read -p "是否确定恢复默认主题？（恢复后会重启）[Y/n]：" YN
+echo -e "\n q. 返回(return)"
+read -p "是否恢复默认主题并重启?(Do you want to restore the default theme and restart?)[Y/n]:" YN
+
 case ${YN} in
 [Yy]) 
-    ER "恢复默认主题中，将重启系统。"
+    ER "已恢复默认主题，重启系统中(The default theme has been restored. Restart the system)..."
     uci set luci.main.mediaurlbase='/luci-static/bootstrap'
     uci commit luci
     reboot -f
@@ -61,11 +69,15 @@ case ${YN} in
 break
 ;;
 [Nn])
-    EW "取消返回主菜单"
+    EW "返回主菜单(return)"
+    . /etc/profile
+
+;;
+[Qq])
     . /etc/profile
 ;;
 *)
-    ER "输入正确选择[Y/n]"
+    ER "输入正确选择(Enter the correct choice!)"
 ;;
 esac
 done
@@ -74,27 +86,31 @@ done
 function k_poweroff() {
 echo
 while :; do
-read -p "是否确定关闭系统？[Y/n]：" YN
+echo -e "\n q. 返回(return)"
+read -p "是否确定关闭系统？(Are you sure to shut down the system)[Y/n]:" YN
 case ${YN} in
 [Yy]) 
-    ER "正在关闭系统中，请稍等..."
+    ER "正在关闭系统中，请稍等(Shutting down the system, please wait)..."
     sync && poweroff
     break
 ;;
 [Nn])
-    EW "取消返回主菜单"
+    EW "返回主菜单(return)"
+    . /etc/profile
+;;
+[Qq])
     . /etc/profile
 ;;
 *)
-    ER "输入正确选择[Y/n]"
+    ER "输入正确选择(Enter the correct choice!)"
 ;;
 esac
 done
 }
 
 function k_change_ip() {
-  echo
-  export k_ip="请输入您想要更改成的后台IP[q返回]:"
+  echo -e "\n q. 返回(return)"
+  export k_ip="请输入改成IP(Please change the input to IP)"
   echo
   while :; do
   domainy=""
@@ -109,24 +125,28 @@ function k_change_ip() {
   Y)
     export keyipn="${keyip}"
     uci set network.lan.ipaddr="${keyip}"
-    ER "您的IP已经改为：${keyip},已经生效！"
+    ER "您的IP已经改成(Your IP has been changed to)：${keyip}！"
     uci commit network
     /etc/init.d/network restart
     break
   ;; 
-  Q)
+
+ Q)
     . /etc/profile
-  ;;
-  *)
-    export k_ip="请输入正确格式的IP地址[q返回]"
+;;
+
+  *) 
+  echo -e "\n q. 返回(return)"
+  export k_ip="输入正确格式IP地址[x.x.x.x](enter IP address format[x.x.x.x])"
   ;;
   esac
   done
 }
 
 function k_clear() {
-while :; do
-read -p "否清空密码并重启？[Y/n]：" YN
+while :; do 
+echo -e "\n q. 返回(return)"
+read -p "否清空密码并重启？(Clear password and Reboot)[Y/n]：" YN
 case ${YN} in
 [Yy]) 
     if [[ "$USER" == "admin" ]]; then
@@ -139,11 +159,14 @@ case ${YN} in
 break
 ;;
 [Nn])
-    EW "取消返回主菜单"
+    EW "返回主菜单(return)"
+    . /etc/profile
+;;
+[Qq])
     . /etc/profile
 ;;
 *)
-    ER "输入正确选择!"
+    ER "输入正确选择!(Enter the correct choice!)"
 ;;
 esac
 done
@@ -152,10 +175,11 @@ done
 function k_reboot() {
 echo
 while :; do
-read -p "是否重启系统[Y/n]：" YN
+echo -e "\n q. 返回(return)"
+read -p "是否重启系统(Whether to restart the system)[Y/n]:" YN
 case ${YN} in
 [Yy]) 
-    ER "系统重启中..."
+    ER "系统重启中(System is restarting)..."
     uci set argon.@global[0].bing_background=0
     uci commit argon
     reboot -f
@@ -163,11 +187,14 @@ case ${YN} in
 break
 ;;
 [Nn])
-    EW "取消返回主菜单"
+    EW "返回主菜单(return)"
+    . /etc/profile
+;;
+[Qq])
     . /etc/profile
 ;;
 *)
-    ER "输入正确选择!"
+    ER "输入正确选择!(Enter the correct choice!)"
 ;;
 esac
 done
@@ -176,32 +203,60 @@ done
 function k_firstboot() {
 echo
 while :; do
-read -p "是否恢复出厂设置?按[Y/y]执行,按[N/n]退出：" YN
+echo -e "\n q. 返回(return)"
+read -p "是否恢复出厂设置(Restore factory settings)?[Y/y]or[N/n]:" YN
 case ${YN} in
 [Yy]) 
-    ER "已经恢复出厂设置,系统重启中..." 
+    ER "已经恢复出厂设置,系统重启中(The factory settings have been restored, and the system is restarting)..." 
     firstboot -y
     reboot -f
     goreboot
 break
 ;;
 [Nn])
-    EW "取消返回主菜单"
+    EW "取消返回主菜单(return)"
+    . /etc/profile
+;;
+[Qq])
     . /etc/profile
 ;;
 *)
-    ER "输入正确选择!"
+    ER "输入正确选择!(Enter the correct choice!)"
 ;;
 esac
 done
 }
 
+function Check_Pkg() {
+	while [[ $1 ]];do
+		CMD=$(echo $1 | cut -d ':' -f1)
+		PKG=$(echo $1 | cut -d ':' -f2)
+		[[ -z ${PKG} ]] && PKG=${CMD}
+		if [[ $(CHECK_PKG ${CMD}) == false ]]
+		then
+			if_False=1
+			ECHO r "\n缺少软件包(Missing package):[${PKG}]"
+		fi
+		shift
+	done
+	if [[ ${if_False} == 1 ]]
+	then
+		sleep 2
+		return 1
+	else
+		return 0
+	fi
+}
+function CHECK_PKG() {
+	which $1 > /dev/null 2>&1
+	[[ $? == 0 ]] && echo true || echo false
+}
 goreboot() {
   if [[ 0 -eq $? ]]; then
-    ER "$1 完成,正在为您重启系统"
+    ER "$1 完成,正在为您重启系统(Done, restarting the system for you)"
     reboot -f
   else
-    ER "$1 失败"
+    ER "$1 失败 (invalid)"
     exit 0
   fi
 }
@@ -253,19 +308,26 @@ in order to prevent unauthorized SSH logins.
 ------------------------------------------------
 EOF
 fi
+
+alias menu='. /etc/profile'
+alias shutdown='sync && poweroff'
+alias dh='df -h'
+alias ls='ls --color=auto'
+alias top='top -d 1'
+
 function mainmenu() {
-  echo  
-  EB "   Sirdpboy快捷命令菜单  "
-  EG " menu ->重进菜单   top ->查看进程 "
-  EY " 1. 修改后台IPV4地址(set IPv4)"
-  EY " 2. 清除密码并重启(clear password)"
-  EY " 3. 恢复默认主题(restore_theme)"
-  EY " 4. 重启系统(reboot)"
-  EY " 5. 强制关机(shutdown)"
-  EY " 6. 恢复出厂设置(firstboot)"
-  ER " 9. 退出菜单(exit)"
+  EB "     Sirdpboy快捷命令菜单(Shortcut Command Menu)   "
+  EG " menu->重进菜单(Reentry menu)   top->查看进程(View Processes) "
+  EY " 1. 修改后台IPv4地址(Modify IPv4 address)"
+  EY " 2. 清除密码并重启(Clear password and Reboot)"
+  EY " 3. 恢复默认主题(Restore default theme)"
+  EY " 4. 重启服务器(Reboot)"
+  EY " 5. 关闭服务器(Shutdown)"
+  EY " 6. 恢复出厂设置(Restore factory settings)"
+  EY " 7. 网络连接检查(Check network connectivity)"
+  ER " 9. 退出菜单(Exit)"
   echo
-  KEY="请输入数字"
+  KEY="请输入数字(please enter a number)"
   while :; do
   read -p " ${KEY}： " CHOOSE
   case $CHOOSE in
@@ -293,21 +355,33 @@ function mainmenu() {
       k_firstboot
     break
     ;;
+    7)
+	ping 114.114.114.114 -c 1 -W 2 > /dev/null 2>&1 && \
+	EY  " 基础114网络连接正常!(Basic 114 network connection is OK!)" || EG  " 基础114网络连接错误!(Basic 114 network connection error!)"
+	nslookup -type=a baidu.com > /dev/null 2>&1 &&\
+	EY  " 基础 IPv4 DNS 解析正常!(Basic IPv4 DNS resolution is OK!)" || EG  " 基础 IPv4 DNS 解析错误!(Basic IPv4 DNS resolution error!)"
+	Google_Check=$(curl -I -s --connect-timeout 3 http://www.google.com/generate_204 -w %{http_code} | tail -n1)
+			
+	case ${Google_Check} in
+	204)
+		EY " Google 连接正常!(Google connection is OK!)"
+	;;
+	*)
+		EG " Google 连接错误!(Google connection is error!)"
+	;;
+		esac
+		ER " "
+		sleep 2
+	;;
     9)
-      EW "您选择了退出程序"
+      EW " 退出程序成功(Exit the program successfully)"
+      echo
       break
     ;;
     *)
-      KEY="请输入正确的数字编号:"
+     KEY="请输入数字(please enter a number)"
     ;;
     esac
     done
 }
-
-alias menu='. /etc/profile'
-alias shutdown='sync && poweroff'
-alias dh='df -h'
-alias ls='ls --color=auto'
-alias top='top -d 1'
-
 mainmenu
