gx

diff --git a/up/pass/luci-app-bypass/root/etc/init.d/bypass b/up/pass/luci-app-bypass/root/etc/init.d/bypass
--- a/up/pass/luci-app-bypass/root/etc/init.d/bypass
+++ b/up/pass/luci-app-bypass/root/etc/init.d/bypass
@@ -59,7 +59,7 @@ socks5_ip=''
 gen_log()(
 
 	[ -s $LOG ] && echo '------------start------------' >> $LOG
-	log "Check network status..."
+	log "Check network status."
 )
 
 log(){
@@ -263,9 +263,25 @@ get_soip(){
 		if [ "$1" = 1 ];then
 			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status...' || gen_log
 			check_net
-			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status success!' || log "Rules      : Check network status success!"
+			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status successful!' || log "Rules      : Check network status successful!"
 		fi
-		socks5_ip=$(host_ip $SO_SERVER)
+		socks5_ip=$(uci_get_by_name $SO_SERVER server)
+		if ! echo $socks5_ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
+			if [ -f $LOCK ];then
+				r=1
+				while ! nslookup $socks5_ip >/dev/null 2>&1;do
+					[ $r -ge 20 ] && return 1 || let r++
+					sleep 1
+				done
+			fi
+			if ! A=$(nslookup $socks5_ip 2>/dev/null | grep Address | awk -F' ' '{print$NF}' | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$");then
+			  log "Rules      : Get $(uci_get_by_name $1 alias) ip:$ip success!" 
+			else
+				  log "Rules      : Unable to get server address.Check domain name!"
+				  exit 1
+			fi
+			socks5_ip=$(echo "$A" | sed -n 1p)
+		fi
 	fi
 }
 
@@ -280,12 +296,12 @@ rules(){
 	fi
 	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status.\|Download IP/GFW files.' || gen_log
 	check_net
-	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "Rules      : Check network status success!";log "Rules      : Check IP/GFW files...")
+	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "Rules      : Check network status successful!";log "Rules      : Check IP/GFW files...")
 	[ ! -d $VAR  ] && mkdir -p $VAR
 	[ ! -d /tmp/run ] &&  mkdir -p /tmp/run 
 	[ ! -s $VAR/china.txt ] || [ ! -s $VAR/china_v6.txt ] || [ ! -s $VAR/gfw.list ] && {
 		if [ ! -s $T_FILE/china.txt ] || [ ! -s $T_FILE/china_v6.txt ] || [ ! -s $T_FILE/gfw.list ] ;then
-			log "Rules      :Download IP/GFW files..."
+			log "Rules      : Download IP/GFW files."
 			$BIN_DIR/update --f ;exit 0;
 		else
 			cp -f $T_FILE/*.txt $VAR
